### ISSUE TITLE
cannot find or open .serverless/stack-stage-function, .serverless/stack-stage-function.zip or .serverless/stack-stage-function.ZIP.

### ISSUE THREAD

**Issue by smbkr** [adriencaccia/serverless-analyze-bundle-plugin#1]
It looks as though the plugin is searching for a file named `.serverless/stack-stage-function.zip` or similar, however with my config, `serverless-esbuild` outputs a file named `.serverless/function.zip`

Serverless:
  Framework Core: 2.70.0 (local)
  Plugin: 5.5.3
  SDK: 4.3.0
  Components: 3.18.1

esbuild: 0.14.21

severless-esbuild: 1.24.1

esbuild-visualiser: 0.3.1

serverless-analyze-bundle-plugin: 1.0.5

`serverless.yml`:

```yml
service: my-api
frameworkVersion: '2'
variablesResolutionMode: 20210326

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage}
  region: eu-west-1
  
plugins:
  - serverless-esbuild
  - serverless-analyze-bundle-plugin

functions:
  foobar:
    description: Foobar function
    handler: src/handlers/foo.main

custom:
  esbuild:
    packager: yarn
    bundle: true
    minify: true
    target: node14
    sourcemap: external
```
